// Generated by https://quicktype.io

export interface Details {
    tamil: string;
    section: Section;
    repo: string;
}

export interface SectionDetail {
    name: string;
    transliteration: string;
    translation: string;
    number: number;
    chapterGroup?: Section;
    chapters?: Chapters;
}

export interface Section {
    tamil: string;
    detail: SectionDetail[];
}

export interface Chapters {
    tamil: any;
    detail: ChaptersDetail[];
}

export interface ChaptersDetail {
    name: string;
    translation: string;
    transliteration: string;
    number: number;
    start: number;
    end: number;
}

